name: Main workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  setup-node:
    needs: build
    uses: ./.github/workflows/setup-node.yml

  lint:
    needs: setup-node
    uses: ./.github/workflows/lint.yml

  test:
    needs: lint
    uses: ./.github/workflows/test.yml

  sonarcloud:
    needs: test
    uses: ./.github/workflows/sonarcloud.yml
    secrets: inherit

  docker:
    needs: [setup-node, lint, test, sonarcloud]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
