name: Main workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  setup-node:
    needs: build
    uses: ./.github/workflows/setup-node.yml

  lint:
    needs: setup-node
    uses: ./.github/workflows/lint.yml

  docker:
    needs: [setup-node, lint, sonarcloud]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
