name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  setup-node:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run tests
        run: npm test

  build-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build Docker image
        run: docker build . -t your-docker-repo/your-image-name:${{ github.sha }}

  push-docker:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push your-docker-repo/your-image-name:${{ github.sha }}

  sonarcloud-scan:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
